language: node_js
node_js:
  - "10"
before_install:
  - npm install -g npm@6
  - npm install -g grunt-cli bower
install:
  - npm install
  - bower install
script: grunt build && grunt test && grunt coveralls
