name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run grunt tests
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.17'

      - name: Install npm
        run: npm install -g npm@6    

      - name: Install grunt + bower
        run: npm install -g grunt-cli bower

      - name: Run npm install
        run: npm install

      - name: Run bower install
        run: bower install

      - name: Run tests
        run: grunt build && grunt test
